server:
  port: 7002
  servlet:
    context-path: /coupon-distribution

spring:
  application:
    name: eureka-client-coupon-distribution
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    # 数据源
    url: jdbc:mysql://mysqqqqql:3306/coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: CouponHikariCP
  redis:
    database: 0
    host: rediiiiis
    port: 6379
    # password:
    # 连接超时时间
    timeout: 10000
  kafka:
    bootstrap-servers:
      - kafkkkkka:9092
    consumer:
      group-id: coupon-x
      auto-offset-reset: latest
  # 开启 ribbon 重试机制, 即获取服务失败是否从另外一个节点重试
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/

logging:
  level:
    com.zing.coupon: debug

feign:
  hystrix:
    # Hystrix 默认是关闭的
    enabled: true
  client:
    config:
      # 全局的
      default:
        # 默认的连接超时时间是 10s
        connectTimeout: 2000
        readTimeout: 5000
      # 单独服务的配置
      eureka-client-coupon-template:
        # 默认的连接超时时间是 10s
        connectTimeout: 3000
        readTimeout: 5000
