server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logbook:
  write:
    level: info
  format:
    style: http
#logging:
#  config: classpath:log4j2.xml
spring:
  application:
    name: user
  druid:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    max-active: 20
    min-idle: 3
    max-wait: 10000
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
  redis:
    host: 192.168.110.128
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 5
  mail:
    host: smtp.163.com
    username: cyunzing@163.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#  sleuth:
#    sampler:
#      probability: 1
#  zipkin:
#    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8666/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
file:
  #\u672C\u5730\u5B58\u653E\u7684\u6587\u4EF6\u8DEF\u5F84,\u53EF\u4EE5\u4FEE\u6539\u6210\u81EA\u5DF1\u7684\u56FE\u7247\u5B58\u653E\u8DEF\u5F84,\u5BF9\u5E94nginx.conf\u91CCalias\u5BF9\u5E94\u76EE\u5F55(\u82E5\u672C\u5730\u5B89\u88C5\u4E86nginx\u670D\u52A1\u5668,\u5F00\u542F\u5982\u4E0B\u914D\u7F6E)
  path: I:/tmp/imgs
  #\u9759\u6001\u8D44\u6E90\u5730\u5740\u524D\u7F00(\u82E5\u672C\u5730\u5B89\u88C5\u4E86nginx\u670D\u52A1\u5668,\u5F00\u542F\u5982\u4E0B\u914D\u7F6E)
  prefix: http://127.0.0.1:8081/images

user.service.name: user
house.service.name: house
comment.service.name: comment