spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/cyunzing/config-repo
  rabbitmq:
    host: 192.168.110.129
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"